language: node_js
node_js:
- 11
- 10
- 9
- 8
after_success:
- npm run coveralls
env:
  global:
    secure: hsMpJHQ2T0KjQsKO6IHiLyCA44JCh3cwWAb2SVxnumhw5y+OyzSPaA7I906BN6rq3akfcf1IllM+uzNuGceoLJHKfSif9luZWm3KHp6q1pYk5zMX3p3uFmCI4q+6lrU8ujxBTv5Piv2wg+nknshy16n7G+VNvKVF7SDnraqh5AZlICPeCTCkCH3nfdoqG6zDukGqvef8whsqokfTztchMgtY742TzwSMsjddhbPoKN4zxlrrb8Y9ACdSqN5mOXPTZx1FBUtO2iRoZEi1KA8rr9JX6cqUae0DjUhPlfVKqBYeTaMEx9dsj4uC8gljw8eh2kR+DZ+41fKf/etOj+tMHRrlIDiEqwiaH0AoMWJxSic1Y4+nszlcMibrEpEi24TuMlE2dBtMVSjkinnfMHCz6Oejo2RfcIF4i/NATz6hbFuMqFVlD7Wr0VSpHUQzat1JJ75VO77D8snIl/oO3AeGEivm03FVUnRY4aiylBGOQ0CBVN74iar0ktW8DDpOPezd012DpF5dId3mCjkEsv3K/sOZHNHc3FlXaqcu03fGDfu7JCo+FE707Pp7vEWWQBrEDl57R/PIW/jSju6tf9qttSlxrWS5TKxTWNll1x53BrhvTVhVqGi5ZXIlLTfKdPiCJukv/DmK1kFb2GJNGk4a6dPTSeVjmf3yFf87miHCquQ=
